const SB_URL="https://puxzsxhrlghbzatzsiyg.supabase.co";
const SB_KEY="sb_publishable_u0gjKD7XY4z5v5B1-vKFww_0EYGuX22";
const supa=window.supabase.createClient(SB_URL,SB_KEY);
const S={brand:localStorage.brand||"#ff7a00",shop:localStorage.shop||"Mi Taller",user:null,profile:null,current:"Dashboard"};
document.documentElement.style.setProperty("--brand",S.brand);
const modules=["Dashboard","Órdenes","Clientes","Empleados","Cotizaciones","Recibos","Inventario","Reportes","Ajustes"];
const esc=v=>String(v??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#039;"}[m]));
const statusLabel=s=>({pending:"Pendiente",assigned:"Asignada",en_route:"En camino",diagnosis:"Diagnóstico",waiting_parts:"Esperando piezas",repair:"En reparación",quality_check:"Control calidad",completed:"Completada",cancelled:"Cancelada"}[s]||s||"");
async function init(){const {data:{session}}=await supa.auth.getSession();if(session){S.user=session.user;await loadProfile();}render();supa.auth.onAuthStateChange(async(_,session)=>{S.user=session?.user||null;if(S.user)await loadProfile();else S.profile=null;render()})}
async function loadProfile(){await supa.rpc("claim_initial_admin");const {data}=await supa.from("profiles").select("*").eq("id",S.user.id).single();S.profile=data}
async function login(){const email=document.querySelector("#email").value.trim();const password=document.querySelector("#pass").value;const {error}=await supa.auth.signInWithPassword({email,password});if(error)alert(error.message)}
const ADMIN_REDIRECT="https://eliezelapolinaris2017-lab.github.io/-taller-admin/";
async function signup(){const email=document.querySelector("#email").value.trim();const password=document.querySelector("#pass").value;if(password.length<8)return alert("La contraseña debe tener al menos 8 caracteres.");const {data,error}=await supa.auth.signUp({email,password,options:{data:{full_name:"Administrador"},emailRedirectTo:ADMIN_REDIRECT}});if(error)return alert(error.message);localStorage.pendingAdminEmail=email;alert(data.session?"Cuenta creada. Entrando...":"Cuenta creada. Revisa el email de confirmación. El enlace regresará al panel administrativo.")}
async function resendConfirmation(){const email=(document.querySelector("#email")?.value||localStorage.pendingAdminEmail||"").trim();if(!email)return alert("Escribe el email de administrador.");const {error}=await supa.auth.resend({type:"signup",email,options:{emailRedirectTo:ADMIN_REDIRECT}});if(error)return alert(error.message);alert("Te envié un enlace nuevo de confirmación. Usa solamente el más reciente.")}
async function logout(){await supa.auth.signOut()}
function authView(){return '<div class="login"><div class="card"><div class="brand"><div class="mark">TA</div><span>Taller Admin</span></div><p class="muted">Acceso administrativo seguro</p><label>Email</label><input id="email" type="email" placeholder="admin@taller.com"><label>Contraseña</label><input id="pass" type="password" placeholder="8+ caracteres"><button class="btn" onclick="login()">Entrar</button> <button class="btn secondary" onclick="signup()">Crear primer administrador</button><button class="btn secondary" style="margin-top:10px;width:100%" onclick="resendConfirmation()">Reenviar confirmación</button><p class="muted small">La primera cuenta creada puede reclamar el rol de administrador. Si un enlace expiró, usa Reenviar confirmación y abre solamente el email más reciente.</p></div></div>'}
function render(){const a=document.querySelector("#app");if(!S.user){a.innerHTML=authView();return}if(!S.profile||!["admin","manager"].includes(S.profile.role)){a.innerHTML='<div class="login"><div class="card"><h2>Acceso restringido</h2><p>Esta cuenta no tiene permisos administrativos.</p><button class="btn" onclick="logout()">Salir</button></div></div>';return}a.innerHTML='<div class="shell"><aside class="side"><div class="brand"><div class="mark">TA</div><span>'+esc(S.shop)+'</span></div><div class="nav">'+modules.map(m=>'<button data-n="'+m+'" class="'+(m===S.current?"active":"")+'" onclick="nav(\''+m+'\')">'+m+'</button>').join("")+'</div></aside><main class="main"><div class="top"><div><b>Panel administrativo</b><div class="muted">'+esc(S.profile.full_name||S.user.email)+' · '+esc(S.profile.role)+'</div></div><button class="btn" onclick="logout()">Salir</button></div><section id="content"><div class="card">Cargando...</div></section></main></div>';content(S.current)}
function nav(name){S.current=name;render()}
async function content(name){const c=document.querySelector("#content");if(!c)return;if(name==="Dashboard")return dashboard(c);if(name==="Órdenes")return orders(c);if(name==="Clientes")return customers(c);if(name==="Empleados")return employees(c);if(name==="Inventario")return inventory(c);if(name==="Cotizaciones")return quotes(c);if(name==="Recibos")return receipts(c);if(name==="Reportes")return reports(c);if(name==="Ajustes")return settings(c)}
async function dashboard(c){const [{count:orders},{count:pending},{count:customers},{count:low}]=await Promise.all([supa.from("work_orders").select("*",{count:"exact",head:true}),supa.from("work_orders").select("*",{count:"exact",head:true}).neq("status","completed").neq("status","cancelled"),supa.from("customers").select("*",{count:"exact",head:true}),supa.from("inventory_items").select("*",{count:"exact",head:true}).lte("quantity",0)]);const {data:recent}=await supa.from("work_orders").select("id,order_number,title,status,created_at,vehicles(make,model,year)").order("created_at",{ascending:false}).limit(6);c.innerHTML='<div class="heroBanner"><div class="heroCopy"><div class="eyebrow">Luxury Garage Tech</div><h2>Control total. Imagen premium.</h2><p>Administra órdenes, clientes, personal e inventario desde una experiencia diseñada para talleres que quieren crecer.</p><span class="heroTag">OPERACIÓN EN TIEMPO REAL</span></div></div><h1>Dashboard</h1><p class="muted">Resumen ejecutivo del taller.</p><div class="grid"><div class="metric">Órdenes activas<strong>'+(orders||0)+'</strong><small>Operación total</small></div><div class="metric">En proceso<strong>'+(pending||0)+'</strong><small>Seguimiento activo</small></div><div class="metric">Clientes<strong>'+(customers||0)+'</strong><small>Base registrada</small></div><div class="metric">Inventario crítico<strong>'+(low||0)+'</strong><small>Requiere atención</small></div></div><div class="dashboardActivity"><div class="card sectionCard"><div class="sectionTitle"><h3>Actividad reciente</h3><span class="pill">En vivo</span></div><div class="list">'+((recent||[]).slice(0,4).map(o=>'<div class="row"><span><b>OT-'+o.order_number+'</b><br><span class="muted">'+esc(o.title)+'</span></span><span class="pill">'+esc(statusLabel(o.status))+'</span></div>').join("")||'<p class="muted">Aún no hay órdenes.</p>')+'</div></div><div class="card sectionCard"><div class="sectionTitle"><h3>Órdenes de trabajo recientes</h3><span class="muted">Últimos movimientos</span></div><div class="list">'+((recent||[]).map(o=>'<div class="row"><span><b>OT-'+o.order_number+'</b> · '+esc(o.vehicles?.year||"")+' '+esc(o.vehicles?.make||"")+' '+esc(o.vehicles?.model||"")+'<br><span class="muted">'+esc(o.title)+'</span></span><span class="pill">'+esc(statusLabel(o.status))+'</span></div>').join("")||'<p class="muted">Aún no hay órdenes.</p>')+'</div></div></div>'}
async function customers(c){const {data:list}=await supa.from("customers").select("*,vehicles(*)").order("created_at",{ascending:false});c.innerHTML='<div class="sectionHead"><div><h1>Clientes y vehículos</h1><p class="muted">Base maestra del taller.</p></div><button class="btn" onclick="showCustomerForm()">+ Cliente</button></div><div id="customerForm"></div><div class="list">'+((list||[]).map(x=>'<div class="card"><div class="row"><b>'+esc(x.name)+'</b><span class="muted">'+esc(x.phone||"")+'</span></div><div class="muted">'+esc(x.email||"")+'</div><div class="chips">'+(x.vehicles||[]).map(v=>'<span class="pill">'+esc(v.year||"")+' '+esc(v.make||"")+' '+esc(v.model||"")+' '+esc(v.plate||"")+'</span>').join(" ")+'</div><button class="btn smallbtn" onclick="showVehicleForm(\''+x.id+'\',\''+esc(x.name).replace(/'/g,"&#39;")+'\')">+ Vehículo</button></div>').join("")||'<div class="card muted">No hay clientes.</div>')+'</div>'}
function showCustomerForm(){document.querySelector("#customerForm").innerHTML='<div class="card formcard"><h3>Nuevo cliente</h3><div class="formgrid"><input id="cn" placeholder="Nombre"><input id="cp" placeholder="Teléfono"><input id="ce" type="email" placeholder="Email"><input id="ca" placeholder="Dirección"></div><button class="btn" onclick="saveCustomer()">Guardar cliente</button></div>'}
async function saveCustomer(){const payload={name:document.querySelector("#cn").value.trim(),phone:document.querySelector("#cp").value.trim(),email:document.querySelector("#ce").value.trim(),address:document.querySelector("#ca").value.trim(),created_by:S.user.id};if(!payload.name)return alert("Nombre requerido");const {error}=await supa.from("customers").insert(payload);if(error)return alert(error.message);customers(document.querySelector("#content"))}
function showVehicleForm(cid,name){document.querySelector("#customerForm").innerHTML='<div class="card formcard"><h3>Nuevo vehículo · '+name+'</h3><div class="formgrid"><input id="vy" type="number" placeholder="Año"><input id="vmk" placeholder="Marca"><input id="vmd" placeholder="Modelo"><input id="vpl" placeholder="Tablilla"><input id="vvin" placeholder="VIN"><input id="vmi" type="number" placeholder="Millaje"></div><button class="btn" onclick="saveVehicle(\''+cid+'\')">Guardar vehículo</button></div>'}
async function saveVehicle(cid){const p={customer_id:cid,year:+document.querySelector("#vy").value||null,make:document.querySelector("#vmk").value.trim(),model:document.querySelector("#vmd").value.trim(),plate:document.querySelector("#vpl").value.trim(),vin:document.querySelector("#vvin").value.trim(),mileage:+document.querySelector("#vmi").value||null};const {error}=await supa.from("vehicles").insert(p);if(error)return alert(error.message);customers(document.querySelector("#content"))}
async function orders(c){const [{data:list},{data:customers},{data:profiles}]=await Promise.all([supa.from("work_orders").select("*,customers(name),vehicles(year,make,model,plate),work_order_assignments(user_id,profiles(full_name))").order("created_at",{ascending:false}),supa.from("customers").select("id,name,vehicles(id,year,make,model,plate)").order("name"),supa.from("profiles").select("id,full_name,role").eq("active",true).order("full_name")]);window._orderCustomers=customers||[];window._profiles=profiles||[];c.innerHTML='<div class="sectionHead"><div><h1>Órdenes de trabajo</h1><p class="muted">Asignación y seguimiento operativo.</p></div><button class="btn" onclick="showOrderForm()">+ Orden</button></div><div id="orderForm"></div><div class="list">'+((list||[]).map(o=>'<div class="card"><div class="row"><div><b>OT-'+o.order_number+' · '+esc(o.title)+'</b><div class="muted">'+esc(o.customers?.name||"")+' · '+esc(o.vehicles?.year||"")+' '+esc(o.vehicles?.make||"")+' '+esc(o.vehicles?.model||"")+'</div></div><span class="pill">'+esc(statusLabel(o.status))+'</span></div><div class="muted">Asignado: '+esc((o.work_order_assignments||[]).map(a=>a.profiles?.full_name).filter(Boolean).join(", ")||"Sin asignar")+'</div><div class="actions"><select id="st-'+o.id+'"><option value="'+o.status+'">'+statusLabel(o.status)+'</option>'+["pending","assigned","en_route","diagnosis","waiting_parts","repair","quality_check","completed","cancelled"].filter(s=>s!==o.status).map(s=>'<option value="'+s+'">'+statusLabel(s)+'</option>').join("")+'</select><button class="btn smallbtn" onclick="updateOrderStatus(\''+o.id+'\')">Actualizar</button></div></div>').join("")||'<div class="card muted">No hay órdenes.</div>')+'</div>'}
function showOrderForm(){const cs=window._orderCustomers||[],ps=window._profiles||[];document.querySelector("#orderForm").innerHTML='<div class="card formcard"><h3>Nueva orden</h3><label>Cliente / vehículo</label><select id="ov"><option value="">Seleccione...</option>'+cs.flatMap(c=>(c.vehicles||[]).map(v=>'<option value="'+v.id+'" data-c="'+c.id+'">'+esc(c.name)+' · '+esc(v.year||"")+' '+esc(v.make||"")+' '+esc(v.model||"")+' '+esc(v.plate||"")+'</option>')).join("")+'</select><input id="ot" placeholder="Trabajo / título"><textarea id="oc" rows="3" placeholder="Queja o solicitud del cliente"></textarea><label>Asignar empleado</label><select id="oa"><option value="">Sin asignar</option>'+ps.filter(p=>["mechanic","helper","manager"].includes(p.role)).map(p=>'<option value="'+p.id+'">'+esc(p.full_name||p.role)+'</option>').join("")+'</select><button class="btn" onclick="saveOrder()">Crear orden</button></div>'}
async function saveOrder(){const sel=document.querySelector("#ov"),vehicle_id=sel.value,customer_id=sel.selectedOptions[0]?.dataset.c,title=document.querySelector("#ot").value.trim(),assignee=document.querySelector("#oa").value;if(!vehicle_id||!title)return alert("Selecciona vehículo y escribe el trabajo.");const {data,error}=await supa.from("work_orders").insert({customer_id,vehicle_id,title,complaint:document.querySelector("#oc").value.trim(),status:assignee?"assigned":"pending",created_by:S.user.id}).select().single();if(error)return alert(error.message);if(assignee)await supa.from("work_order_assignments").insert({work_order_id:data.id,user_id:assignee,assigned_by:S.user.id});orders(document.querySelector("#content"))}
async function updateOrderStatus(id){const status=document.querySelector("#st-"+id).value;const patch={status,updated_at:new Date().toISOString()};if(status==="completed")patch.completed_at=new Date().toISOString();const {error}=await supa.from("work_orders").update(patch).eq("id",id);if(error)return alert(error.message);orders(document.querySelector("#content"))}
async function employees(c){const {data:list}=await supa.from("profiles").select("*").order("created_at");c.innerHTML='<div class="sectionHead"><div><h1>Empleados</h1><p class="muted">Usuarios y permisos del taller.</p></div><button class="btn" onclick="showEmployeeForm()">+ Empleado</button></div><div id="employeeForm"></div><div class="list">'+((list||[]).map(p=>'<div class="row"><span><b>'+esc(p.full_name||p.email)+'</b><br><span class="muted">'+esc(p.email||"")+'</span></span><span class="pill">'+esc(p.role)+'</span></div>').join(""))+'</div>'}
function showEmployeeForm(){document.querySelector("#employeeForm").innerHTML='<div class="card formcard"><h3>Crear acceso de empleado</h3><div class="formgrid"><input id="en" placeholder="Nombre completo"><input id="ee" type="email" placeholder="Email"><input id="ep" type="password" placeholder="Contraseña temporal (8+)"><select id="er"><option value="mechanic">Mecánico</option><option value="helper">Ayudante</option><option value="manager">Gerente</option></select></div><button class="btn" onclick="createEmployee()">Crear usuario</button></div>'}
async function createEmployee(){const body={full_name:document.querySelector("#en").value.trim(),email:document.querySelector("#ee").value.trim(),password:document.querySelector("#ep").value,role:document.querySelector("#er").value};const {data,error}=await supa.functions.invoke("create-employee",{body});if(error)return alert(error.message);if(data?.error)return alert(data.error);alert("Empleado creado.");employees(document.querySelector("#content"))}
async function inventory(c){const {data:list}=await supa.from("inventory_items").select("*").order("name");c.innerHTML='<div class="sectionHead"><div><h1>Inventario</h1><p class="muted">Piezas, consumibles y existencias.</p></div><button class="btn" onclick="showInventoryForm()">+ Artículo</button></div><div id="inventoryForm"></div><div class="list">'+((list||[]).map(i=>'<div class="row"><span><b>'+esc(i.name)+'</b><br><span class="muted">'+esc(i.sku||"")+' · '+esc(i.location||"")+'</span></span><span><b>'+esc(i.quantity)+'</b> uds.</span></div>').join("")||'<div class="card muted">Inventario vacío.</div>')+'</div>'}
function showInventoryForm(){document.querySelector("#inventoryForm").innerHTML='<div class="card formcard"><h3>Nuevo artículo</h3><div class="formgrid"><input id="isk" placeholder="SKU"><input id="inm" placeholder="Nombre"><input id="iq" type="number" step="0.01" placeholder="Cantidad"><input id="irc" type="number" step="0.01" placeholder="Nivel reposición"><input id="ic" type="number" step="0.01" placeholder="Costo"><input id="ip" type="number" step="0.01" placeholder="Precio venta"><input id="il" placeholder="Ubicación"></div><button class="btn" onclick="saveInventory()">Guardar</button></div>'}
async function saveInventory(){const p={sku:document.querySelector("#isk").value.trim()||null,name:document.querySelector("#inm").value.trim(),quantity:+document.querySelector("#iq").value||0,reorder_level:+document.querySelector("#irc").value||0,unit_cost:+document.querySelector("#ic").value||0,sale_price:+document.querySelector("#ip").value||0,location:document.querySelector("#il").value.trim()};if(!p.name)return alert("Nombre requerido");const {error}=await supa.from("inventory_items").insert(p);if(error)return alert(error.message);inventory(document.querySelector("#content"))}
async function quotes(c){const {data:list}=await supa.from("quotes").select("*,customers(name)").order("created_at",{ascending:false});c.innerHTML='<h1>Cotizaciones</h1><div class="list">'+((list||[]).map(q=>'<div class="row"><span>COT-'+q.quote_number+' · '+esc(q.customers?.name||"")+'</span><span>$'+Number(q.total||0).toFixed(2)+' · '+esc(q.status)+'</span></div>').join("")||'<div class="card muted">No hay cotizaciones todavía.</div>')+'</div>'}
async function receipts(c){const {data:list}=await supa.from("receipts").select("*,customers(name)").order("created_at",{ascending:false});c.innerHTML='<h1>Recibos</h1><div class="list">'+((list||[]).map(r=>'<div class="row"><span>REC-'+r.receipt_number+' · '+esc(r.customers?.name||"")+'</span><span>$'+Number(r.amount||0).toFixed(2)+'</span></div>').join("")||'<div class="card muted">No hay recibos todavía.</div>')+'</div>'}
async function reports(c){const [{data:orders},{data:receipts},{data:inventory}]=await Promise.all([supa.from("work_orders").select("status"),supa.from("receipts").select("amount"),supa.from("inventory_items").select("quantity,reorder_level,unit_cost")]);const completed=(orders||[]).filter(o=>o.status==="completed").length,active=(orders||[]).filter(o=>!["completed","cancelled"].includes(o.status)).length,revenue=(receipts||[]).reduce((a,r)=>a+Number(r.amount||0),0),stock=(inventory||[]).reduce((a,i)=>a+Number(i.quantity||0)*Number(i.unit_cost||0),0);c.innerHTML='<h1>Reportes</h1><p class="muted">Indicadores operacionales.</p><div class="grid"><div class="metric">Activas<strong>'+active+'</strong></div><div class="metric">Completadas<strong>'+completed+'</strong></div><div class="metric">Cobrado<strong>$'+revenue.toFixed(2)+'</strong></div><div class="metric">Valor inventario<strong>$'+stock.toFixed(2)+'</strong></div></div>'}
function settings(c){c.innerHTML='<h1>Ajustes</h1><div class="card settings"><div class="logoBox">Logo del taller</div><label>Nombre del negocio</label><input id="shop" value="'+esc(S.shop)+'"><label>Color principal</label><input id="color" type="color" value="'+S.brand+'"><button class="btn" onclick="saveSettings()">Guardar cambios</button></div>'}
function saveSettings(){S.shop=document.querySelector("#shop").value.trim()||"Mi Taller";S.brand=document.querySelector("#color").value;localStorage.shop=S.shop;localStorage.brand=S.brand;document.documentElement.style.setProperty("--brand",S.brand);render()}
init();if("serviceWorker" in navigator)navigator.serviceWorker.register("sw.js");